name: Assign all collaborators to issues with 'everyone' label
on:
    schedule:
        - cron: '0 * * * *' # Every hour
    workflow_dispatch:
permissions:
    issues: write
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
    fetchCurrentIssuesAndCollaborators:
        runs-on: ubuntu-latest
        outputs:
            issues: ${{ steps.fetch-issues.outputs.issues }}
            collaborators: ${{ steps.fetch-collaborators.outputs.collaborators }}
        steps:
            - uses: actions/checkout@v4

            - name: Fetch issues with 'everyone' label
              id: fetch-issues
              run: |
                  issues=$(gh issue list --label everyone --json number | jq -c)
                  echo "issues=$issues" >> $GITHUB_ENV

            - name: Fetch collaborators
              id: fetch-collaborators
              run: |
                  collaborators=$(gh api repos/${{ github.repository }}/collaborators | jq -c)
                  echo "collaborators=$collaborators" >> $GITHUB_ENV

    assignCollaboratorsToIssues:
        needs: fetchCurrentIssuesAndCollaborators
        runs-on: ubuntu-latest
        strategy:
            matrix:
                issue: ${{fromJson(needs.fetchCurrentIssuesAndCollaborators.outputs.issues)}}
                collaborator: ${{fromJson(needs.fetchCurrentIssuesAndCollaborators.outputs.collaborators)}}
        steps:
            - uses: actions/checkout@v4

            - name: Assign collaborator to issue
              run: |
                  issue_number=$(echo ${{ matrix.issue }} | jq -r '.number')
                  collaborator=$(echo ${{ matrix.collaborator }} | jq -r '.login')
                  gh issue edit $issue_number --add-assignee $collaborator

